### ISSUE TITLE
Compatilibidade com IntelliJ 2020.3.2

### ISSUE THREAD

**Issue by luciolucio** [brunobastosg/gerador-cpf-cnpj-intellij-idea#1]
Oi Bruno tudo bom? O plugin não é mais compatível com as versões mais recentes do IntelliJ. Você pretende atualizar?

![Screen Shot 2021-02-23 at 11 32 53](https://user-images.githubusercontent.com/3391093/108858403-e0c85100-75ca-11eb-84ae-f8f8a1b4c7e1.png)

Obrigado
Lúcio

**Comment by brunobastosg** [comment]
Boa tarde. Já tinha percebido isso, vou atualizar sim! Mas obrigado por informar!

**Comment by luciolucio** [comment]
Super obrigado! Seu plugin é extremamente útil :D
