### ISSUE TITLE
Compatibilidade com PHPStorm e outras IDEs da JetBrains

### ISSUE THREAD

**Issue by xthiago** [brunobastosg/gerador-cpf-cnpj-intellij-idea#2]
Seria viável incluir o suporte ao PHPStorm (e/ou outras IDEs da JetBrains)?

**Comment by brunobastosg** [comment]
Ele já suporta, como pode ser visto aqui: https://plugins.jetbrains.com/plugin/10582-gerador-de-cpf-cnpj/versions/stable/137508

Porém, a versão atual não suporta as versões mais recentes dessas IDEs. Acabei de submeter uma nova versão pra JetBrains, e dentro de um ou dois dias, deve estar disponível.

Se funcionar no PHPStorm (o que em tese deve acontecer), você comenta aqui,

**Comment by xthiago** [comment]
Valeu demais Bruno. Será uma grande mão na roda.

**Comment by brunobastosg** [comment]
O pessoal da JetBrains já aprovou o plugin, então pode testar aí.

**Comment by xthiago** [comment]
@brunobastosg funcionou. Muito obrigado :)
